version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      reddit_back:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PORT_UI}:${PORT_UI}/tcp
    networks:
      - reddit_front
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      reddit_back:
        aliases:
          - post_net
      reddit_front:
        aliases:
          - post_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      reddit_back:
        aliases:
          - comment_net
      reddit_front:
        aliases:
          - comment_net
volumes:
  post_db:

networks:
  reddit_front:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24

  reddit_back:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.2.0/24
